### ISSUE TITLE
AccessTokenHandler doesn't work with aspnet HttpClientFactory - should not create default inner handler?

### ISSUE THREAD

**Issue by damianh** [DuendeArchive/IdentityModel#109]
Hey, been exploring the new [HttpClientFactory stuff](https://blogs.msdn.microsoft.com/webdev/2018/02/28/asp-net-core-2-1-preview1-introducing-httpclient-factory/) but with this code... 

    var services = new ServiceCollection();
    services
        .AddHttpClient("client")
        .AddHttpMessageHandler(() => new AccessTokenHandler(
            "https://demo.identityserver.io/connect/token",
            "client",
            "secret",
            "scope"));
    var serviceProvider = services.BuildServiceProvider();
    var httpClientFactory = serviceProvider.GetService<IHttpClientFactory>();
    httpClientFactory.CreateClient("client");

...I get this exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.
Handler: 'IdentityModel.Client.AccessTokenHandler'
  Source=Microsoft.Extensions.Http
  StackTrace:
   at Microsoft.Extensions.Http.HttpMessageHandlerBuilder.CreateHandlerPipeline(HttpMessageHandler primaryHandler, IEnumerable`1 additionalHandlers)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at ConsoleApp1.Program.Main(String[] args) in E:\dev\damianh\IdentityModel2\ConsoleApp1\Program.cs:line 27
```

The reason is because of this check: https://github.com/aspnet/HttpClientFactory/blob/dev/src/Microsoft.Extensions.Http/HttpMessageHandlerBuilder.cs#L78-L80 which, on the face of it, seems reasonable. It also appears that the expected usage of a _delegating_ http message handler is that the InnerHandler is to be set from the outside and is popsicle immutable on first `SendAsync`.
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L53
- https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/DelegatingHandler.cs#L91-L101

Thus I think `AccessTokenHandler` should not create a default inner handler here https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/AccessTokenHandler.cs#L82 . Same would also apply to the `RefreshTokenHandler` here: https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/RefreshTokenHandler.cs#L108

As usual, happy to send a PR removing these if you agree.

**Comment by damianh** [comment]
Runnable code here: https://github.com/damianh/IdentityModel2/blob/httpclientfactory/ConsoleApp1/Program.cs
