### ISSUE TITLE
RequestClientCredentialsAsync error Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader

### ISSUE THREAD

**Issue by ForgeEngineer** [DuendeArchive/IdentityModel#138]
Hi.
 I had a project original in .Net Core 2.0, and updated to .Net Core 2.1.

 **The project runs perfectly when it is in a localhost**, but once I put it in the server I am getting an error when I request the token in this line "var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api1");"  

It says: tokenResponse.Error: **Error reading JObject from JsonReader. Path '', line 0, position 0.**

 So I created a solution from scratch, following the documentation and the examples in identityserver4 quickstart, and I am getting the same exactly error once is in my host.

Here is what the tokenResponse.Exception.StackTrace says:
at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at IdentityModel.Client.Response..ctor(String raw) in C:\local\identity\model\IdentityModel2\src\IdentityModel\Client\Messages\Response.cs:line 22

And this is the short program that I am running to test the idsvr4:

` public class Program
    {
        public static void Main(string[] args) => MainAsync().GetAwaiter().GetResult();

        private static async Task MainAsync()
        {
            // discover endpoints from metadata
            //var disco = await DiscoveryClient.GetAsync("https://localhost:44366/");
            var disco = await DiscoveryClient.GetAsync("https://www.luisbragagnolo.com/");
            if (disco.IsError)
            {
                Console.WriteLine(disco.Error);
                return;
            }

            // request token
            var tokenClient = new TokenClient(disco.TokenEndpoint, "client", "secret");
            var tokenResponse = await tokenClient.RequestClientCredentialsAsync("api1");

            if (tokenResponse.IsError)
            {
                Console.WriteLine(tokenResponse.Error);
                return;
            }

            Console.WriteLine(tokenResponse.Json);
            Console.WriteLine("\n\n");

        }
    }`

The server still is in my host in case your would like to test.

 So I am lost....any help would be appreciated.
Thanks

**Comment by brockallen** [comment]
Check your logs in your token server. Also, check the network traffic and see what content type or payload is returned. It might be html being returned (due to an error and an error page), not JSON.

**Comment by ForgeEngineer** [comment]
Hi brockallen.
 I tried with different tools and I am having the "HTTP/1.1 400 Bad Request" Which I don't understand why. It should be easy and straight forward.

**Comment by brockallen** [comment]
Yes, the logs will make it easy and straight forward to know what the problem is.

**Comment by ForgeEngineer** [comment]
I understand, I found some logs from IIS in my private server, I hope it helps.

#Version: 1.0
#Date: 2018-07-31 18:16:06
#Fields: date time s-ip cs-method cs-uri-stem cs-uri-query s-port cs-username c-ip cs(User-Agent) cs(Referer) sc-status sc-substatus sc-win32-status time-taken
2018-07-31 18:16:06 10.24.242.200 GET /.well-known/openid-configuration - 7000 - 10.24.242.214 - - 200 0 0 1693
2018-07-31 18:16:06 10.24.242.200 GET /.well-known/openid-configuration/jwks - 7000 - 10.24.242.214 - - 200 0 0 58
2018-07-31 18:16:06 10.24.242.200 POST /connect/token - 7000 - 10.24.242.214 - - 400 0 0 420
2018-07-31 18:16:34 10.24.242.200 GET /.well-known/openid-configuration - 7000 - 10.24.242.214 - - 200 0 0 3
2018-07-31 18:16:34 10.24.242.200 GET /.well-known/openid-configuration/jwks - 7000 - 10.24.242.214 - - 200 0 0 7
2018-07-31 18:16:34 10.24.242.200 POST /connect/token - 7000 - 10.24.242.214 - - 400 0 0 120
2018-07-31 18:23:21 10.24.242.200 GET /.well-known/openid-configuration - 7000 - 10.24.242.214 - - 200 0 0 28
2018-07-31 18:23:21 10.24.242.200 GET /.well-known/openid-configuration/jwks - 7000 - 10.24.242.214 - - 200 0 0 3
2018-07-31 18:23:21 10.24.242.200 POST /connect/token - 7000 - 10.24.242.214 - - 400 0 0 65
2018-07-31 18:26:45 10.24.242.200 GET /.well-known/openid-configuration - 7000 - 10.24.242.214 - - 200 0 0 5
2018-07-31 18:26:45 10.24.242.200 GET /.well-known/openid-configuration/jwks - 7000 - 10.24.242.214 - - 200 0 0 12
2018-07-31 18:26:45 10.24.242.200 POST /connect/token - 7000 - 10.24.242.214 - - 400 0 0 67

**Comment by ForgeEngineer** [comment]
Found the problem!!!
 It was the connection to the database, I had a few places as "debugconnection" and "defaultconnection" but I forgot to check if the environment was debug or not.

 Thanks and please feel free to close it.
