### ISSUE TITLE
After upgrade to latest IdentityModel2, began getting error with certificate

### ISSUE THREAD

**Issue by joshmouch** [DuendeArchive/IdentityModel#198]
I've been putting off upgrading to the latest IdentityModel version because when I do, I begin getting an exception about "The remote certificate is invalid according to the validation procedure".  Nothing else in the environment or code changes other than the IdentityModel version.  The full exception is:

```
Exception occurred while processing message.
System.InvalidOperationException: IDX20803: Unable to obtain configuration from: 'https://api-dev.epreop.com/.well-known/openid-configuration'. ---> System.IO.IOException: IDX20804: Unable to retrieve document from: 'https://api-dev.epreop.com/.well-known/openid-configuration'. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.HttpDocumentRetriever.<GetDocumentAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectConfigurationRetriever.<GetAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Protocols.ConfigurationManager`1.<GetConfigurationAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler.<HandleAuthenticateAsync>d__6.MoveNext()
Exception thrown: 'System.InvalidOperationException' in mscorlib.dll
```

If you browse to that URL, you can see that the certificate looks fine.

As a test, I tried adding the following hack, but didn't fix anything.
```
ServicePointManager.ServerCertificateValidationCallback += ... true;
```

**Comment by brockallen** [comment]
> ServicePointManager.ServerCertificateValidationCallback += ... true;

don't do this. fix your environment to properly trust your certs for https. it's an environmental issue.

**Comment by joshmouch** [comment]
@brockallen I agree. That was just a test.  The environment is an Azure App Service, so there's not much I can do to modify it.  The HTTPS certificate seems fine if I browse to it in Chrome/IE.

The only odd thing with the setup is that the same app service is being used to both serve and use the authentication.

**Comment by leastprivilege** [comment]
This error is coming from SslStream/HttpClient - I am not doing anything special to validate HTTPS.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
