### ISSUE TITLE
IDX10501: Signature validation failed. Unable to match key, GetDiscoveryDocumentAsync

### ISSUE THREAD

**Issue by IsmajlMaliqi** [DuendeArchive/IdentityModel#352]
Hello,

The version 5.0.0.preview.0 shows an error while using GetDiscoveryDocumentAsync(...)

**Error Message:**

IDX10501: Signature validation failed. Unable to match key: 
kid: 'System.String'.
Exceptions caught:
 'System.Text.StringBuilder'. 
token: 'System.IdentityModel.Tokens.Jwt.JwtSecurityToken'.

**StackTrace:**

 at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateSignature(String token, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)

Thank you.

**Comment by leastprivilege** [comment]
do you have more details?

**Comment by IsmajlMaliqi** [comment]
Sorry I did not get into details, 
I just rollbacked to the earlier than 5.0 version and it worked.

I may try the upgrade to the 5.0 version again and see the details.

Regards.


> do you have more details?
