### ISSUE TITLE
Method Not found exception after upgrading to 5.0.0

### ISSUE THREAD

**Issue by kooshan** [DuendeArchive/IdentityModel#373]
```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'.
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
```

**Comment by leastprivilege** [comment]
Yes - 5.0 is new major version. Breaking changes are anticipated. 

I will update the introspection handler soon to work with v5 - in the meantime just don't upgrade...

**Comment by leastprivilege** [comment]
Please give this a try
https://www.nuget.org/packages/IdentityModel.AspNetCore.OAuth2Introspection/5.0.0-preview.1

**Comment by kooshan** [comment]
Works as expected! Thanks.
