### ISSUE TITLE
[Question] Is IdentityModel 5.0.1 compatible with IdentityServer4.AccessTokenValidation 3.0.1?

### ISSUE THREAD

**Issue by RNBermudez** [DuendeArchive/IdentityModel#380]
We recently updated our API to .NET 5 and IdentityModel to version 5.0.1 (latest stable available), and noticed that it is failing to validate reference tokens using the introspection endpoint. We are currently using IdentityServer4.AccessTokenValidation 3.0.1 to perform these requests.

The response is always 401, and no introspection logs can be found on the Identity Provider side. Everything works if we downgrade IdentityModel to version 4.6. 

Is this a bug or am I missing something?

Many thanks!

**Comment by iprins** [comment]
Hi, 

Experiencing the same thing when using: 

IdentityModel 5.0.1
IdentityServer4.AccessTokenValidation 3.0.1

We receive the following exception which causes the 401.
```
Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'.
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenIntrospectionResponse> IdentityModel.Client.IntrospectionClient.Introspect(System.String, System.String, System.Collections.Generic.IDictionary`2<System.String,System.String>, System.Threading.CancellationToken)'.
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.LoadClaimsForToken(String token)
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.<>c__DisplayClass9_0.<CreateLazyIntrospection>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at IdentityModel.AspNetCore.OAuth2Introspection.OAuth2IntrospectionHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at IdentityServer4.AccessTokenValidation.IdentityServerAuthenticationHandler.HandleAuthenticateAsync()
```

When using the following, everything works fine.
IdentityModel 4.6.0
IdentityServer4.AccessTokenValidation 3.0.1

**Comment by leastprivilege** [comment]
No it's not. Also - we don't recommend using our authentication handler anymore

https://leastprivilege.com/2020/07/06/flexible-access-token-validation-in-asp-net-core/
