### ISSUE TITLE
NuGet Package Version Mismatch - System.ValueTuple

### ISSUE THREAD

**Issue by dknr** [DuendeArchive/IdentityModel#45]
The NuGet package for [IdentityModel 2.8.0](https://www.nuget.org/packages/IdentityModel/2.8.0) depends on System.ValueTuple 4.3.0. However, the assembly for .NETStandard1.4 references System.ValueTuple 4.0.1. 

This prevents Xamarin on Visual Studio 2017 from building a project that references Identity Model 2.8.0.

Dependency from IdentityModel.2.8.0.nuspec
`<dependency id="System.ValueTuple" version="4.3.0" exclude="Build,Analyzers" />`

Reference from IdentityModel.dll (.NETStandard1.4)
`System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51`
```
typeof(Identity).Assembly.GetReferencedAssemblies()
    .First(a => a.Name == "System.ValueTuple")
    .FullName
```

Excerpt of Xamarin build output
```
5>    Adding assembly reference for IdentityModel, Version=2.8.0.0, Culture=neutral, PublicKeyToken=null, recursively...
5>      Adding assembly reference for System.Security.Claims, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively...
5>      Adding assembly reference for System.Security.Cryptography.Algorithms, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively...
5>      Adding assembly reference for System.Security.Cryptography.X509Certificates, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively...
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error : Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'System.ValueTuple, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Perhaps it doesn't exist in the Mono for Android profile?
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error : File name: 'System.ValueTuple.dll'
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error :    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
5>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1399,2): error :    at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)
```

**Comment by dknr** [comment]
Disregard this - it appears to be an issue with Xamarin's build process.
